version: '3'
services:
  api:
    container_name: 'rensource_api'
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - '8080:80'
    volumes:
      - '/root/RensourceUploads/Blog:/app/wwwroot/Blog'
      - '/root/RensourceUploads/Executives:/app/wwwroot/Executives'
      - '/root/RensourceUploads/Partners:/app/wwwroot/Partners'
      - '/root/RensourceUploads/PressRelease:/app/wwwroot/PressRelease'
      - '/root/RensourceUploads/Projects:/app/wwwroot/Projects'
     
