version: '3'
services:
  api:
    container_name: 'rensource_api'
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - '8080:8080'
      - '4431:4431'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:4431;http://+:8080
      - ASPNETCORE_HTTPS_PORT=4431
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/rencertificate.pfx
    volumes:
      - ./https/rencertificate.pfx:/https/rencertificate.pfx:ro
      - '/home/ubuntu/RensourceImages/RensourceUploads/Blog:/app/wwwroot/Blog'
      - '/home/ubuntu/RensourceImages/RensourceUploads/Executives:/app/wwwroot/Executives'
      - '/home/ubuntu/RensourceImages/RensourceUploads/Partners:/app/wwwroot/Partners'
      - '/home/ubuntu/RensourceImages/RensourceUploads/PressRelease:/app/wwwroot/PressRelease'
      - '/home/ubuntu/RensourceImages/RensourceUploads/Projects:/app/wwwroot/Projects'
      - '/home/ubuntu/RensourceAPILogs:/app/Logs'
     


